In [1]:
import pandas as pd
from sqlalchemy import create_engine
import os
from dotenv import load_dotenv
load_dotenv()

True

In [2]:
df = pd.read_csv("eurocup_2020_results.csv")

In [3]:
df.head()

,stage,date,pens,pens_home_score,pens_away_score,team_name_home,team_name_away,team_home_score,team_away_score,possession_home,possession_away,total_shots_home,total_shots_away,shots_on_target_home,shots_on_target_away,duels_won_home,duels_won_away,events_list,lineup_home,lineup_away
0,Final,11.07.2021,True,3,2,Italy,England,1,1,66%,34%,19,6,6,2,53%,47%,"[{'event_team': 'away', 'event_time': "" 2' "", ...","[{'Player_Name': 'Insigne', 'Player_Number': '...","[{'Player_Name': 'Kane', 'Player_Number': '9'}..."
1,Semi-finals,07.07.2021,False,False,False,England,Denmark,2,1,59%,41%,20,6,10,3,50%,50%,"[{'event_team': 'away', 'event_time': "" 30' "",...","[{'Player_Name': 'Kane', 'Player_Number': '9'}...","[{'Player_Name': 'Krogh Damsgaard', 'Player_Nu..."
2,Semi-finals,06.07.2021,True,4,2,Italy,Spain,1,1,29%,71%,7,16,4,5,49%,51%,"[{'event_team': 'away', 'event_time': "" 51' "",...","[{'Player_Name': 'Insigne', 'Player_Number': '...","[{'Player_Name': 'Torres', 'Player_Number': '1..."
3,Quarter-finals,03.07.2021,False,False,False,Ukraine,England,0,4,48%,52%,7,10,2,6,42%,59%,"[{'event_team': 'away', 'event_time': "" 4' "", ...","[{'Player_Name': 'Yaremchuk', 'Player_Number':...","[{'Player_Name': 'Kane', 'Player_Number': '9'}..."
4,Quarter-finals,03.07.2021,False,False,False,Czech Republic,Denmark,1,2,56%,44%,16,11,5,7,48%,52%,"[{'event_team': 'away', 'event_time': "" 5' "", ...","[{'Player_Name': 'Schick', 'Player_Number': '1...","[{'Player_Name': 'Dolberg', 'Player_Number': '..."

In [4]:
df.dtypes

stage                   object
date                    object
pens                      bool
pens_home_score         object
pens_away_score         object
team_name_home          object
team_name_away          object
team_home_score          int64
team_away_score          int64
possession_home         object
possession_away         object
total_shots_home         int64
total_shots_away         int64
shots_on_target_home     int64
shots_on_target_away     int64
duels_won_home          object
duels_won_away          object
events_list             object
lineup_home             object
lineup_away             object
dtype: object

In [5]:
sth = df["possession_home"][0]
print(sth)

66%

In [4]:
def str_to_int(percentage):
    percentage = int(percentage.replace("%", ""))
    return percentage

columns_to_change = ["possession_home", "possession_away", "duels_won_home", "duels_won_away"]

for i in columns_to_change:
    df[i] = df[i].apply(str_to_int)

In [7]:
df.dtypes

stage                   object
date                    object
pens                      bool
pens_home_score         object
pens_away_score         object
team_name_home          object
team_name_away          object
team_home_score          int64
team_away_score          int64
possession_home          int64
possession_away          int64
total_shots_home         int64
total_shots_away         int64
shots_on_target_home     int64
shots_on_target_away     int64
duels_won_home           int64
duels_won_away           int64
events_list             object
lineup_home             object
lineup_away             object
dtype: object

In [5]:
df["date"] = pd.to_datetime(df["date"]).dt.date
df["date"][17]

datetime.date(2021, 6, 23)

In [9]:
df.dtypes

stage                   object
date                    object
pens                      bool
pens_home_score         object
pens_away_score         object
team_name_home          object
team_name_away          object
team_home_score          int64
team_away_score          int64
possession_home          int64
possession_away          int64
total_shots_home         int64
total_shots_away         int64
shots_on_target_home     int64
shots_on_target_away     int64
duels_won_home           int64
duels_won_away           int64
events_list             object
lineup_home             object
lineup_away             object
dtype: object

In [6]:
print(df.shape)
df.duplicated().value_counts()

(51, 20)

False    51
dtype: int64

In [12]:
df.head()

,stage,date,pens,pens_home_score,pens_away_score,team_name_home,team_name_away,team_home_score,team_away_score,possession_home,possession_away,total_shots_home,total_shots_away,shots_on_target_home,shots_on_target_away,duels_won_home,duels_won_away,events_list,lineup_home,lineup_away
0,Final,2021-11-07,True,3,2,Italy,England,1,1,66,34,19,6,6,2,53,47,"[{'event_team': 'away', 'event_time': "" 2' "", ...","[{'Player_Name': 'Insigne', 'Player_Number': '...","[{'Player_Name': 'Kane', 'Player_Number': '9'}..."
1,Semi-finals,2021-07-07,False,False,False,England,Denmark,2,1,59,41,20,6,10,3,50,50,"[{'event_team': 'away', 'event_time': "" 30' "",...","[{'Player_Name': 'Kane', 'Player_Number': '9'}...","[{'Player_Name': 'Krogh Damsgaard', 'Player_Nu..."
2,Semi-finals,2021-06-07,True,4,2,Italy,Spain,1,1,29,71,7,16,4,5,49,51,"[{'event_team': 'away', 'event_time': "" 51' "",...","[{'Player_Name': 'Insigne', 'Player_Number': '...","[{'Player_Name': 'Torres', 'Player_Number': '1..."
3,Quarter-finals,2021-03-07,False,False,False,Ukraine,England,0,4,48,52,7,10,2,6,42,59,"[{'event_team': 'away', 'event_time': "" 4' "", ...","[{'Player_Name': 'Yaremchuk', 'Player_Number':...","[{'Player_Name': 'Kane', 'Player_Number': '9'}..."
4,Quarter-finals,2021-03-07,False,False,False,Czech Republic,Denmark,1,2,56,44,16,11,5,7,48,52,"[{'event_team': 'away', 'event_time': "" 5' "", ...","[{'Player_Name': 'Schick', 'Player_Number': '1...","[{'Player_Name': 'Dolberg', 'Player_Number': '..."

De momento, me voy a quedar con esta información. Voy a quitar las tres últimas columnas (`events_list`, `lineup_home` y `lineup_away`), porque de momento no voy a usar esos datos. Si los uso, será de otra manera. Voy a añadir una columna vacía, `venue_id`, por si me da tiempo a hacer geoqueries con los estadios en los que se jugó cada partido.

In [7]:
df = df.drop(columns=["events_list", "lineup_home", "lineup_away"])

In [8]:
len(df.index)

51

In [8]:
venues = []
for i in range(0,51):
    venues.append(None)
len(venues)

51

In [9]:
df["venue_id"] = venues

In [23]:
df.head()

,stage,date,pens,pens_home_score,pens_away_score,team_name_home,team_name_away,team_home_score,team_away_score,possession_home,possession_away,total_shots_home,total_shots_away,shots_on_target_home,shots_on_target_away,duels_won_home,duels_won_away,venue_id
0,Final,2021-11-07,True,3,2,Italy,England,1,1,66,34,19,6,6,2,53,47,None
1,Semi-finals,2021-07-07,False,False,False,England,Denmark,2,1,59,41,20,6,10,3,50,50,None
2,Semi-finals,2021-06-07,True,4,2,Italy,Spain,1,1,29,71,7,16,4,5,49,51,None
3,Quarter-finals,2021-03-07,False,False,False,Ukraine,England,0,4,48,52,7,10,2,6,42,59,None
4,Quarter-finals,2021-03-07,False,False,False,Czech Republic,Denmark,1,2,56,44,16,11,5,7,48,52,None

In [10]:
df["team_name_home"] = df["team_name_home"].apply(lambda x: x.strip())
df["team_name_away"] = df["team_name_away"].apply(lambda x: x.strip())

In [11]:
df["stage"] = df["stage"].apply(lambda x: x.strip())

In [13]:
df["team_name_home"][0]

'Italy'

In [12]:
df["match_id"] = df.index
df["match_id"] = df["match_id"].apply(lambda x: x+1)
df.head()

,stage,date,pens,pens_home_score,pens_away_score,team_name_home,team_name_away,team_home_score,team_away_score,possession_home,possession_away,total_shots_home,total_shots_away,shots_on_target_home,shots_on_target_away,duels_won_home,duels_won_away,venue_id,match_id
0,Final,2021-11-07,True,3,2,Italy,England,1,1,66,34,19,6,6,2,53,47,None,1
1,Semi-finals,2021-07-07,False,False,False,England,Denmark,2,1,59,41,20,6,10,3,50,50,None,2
2,Semi-finals,2021-06-07,True,4,2,Italy,Spain,1,1,29,71,7,16,4,5,49,51,None,3
3,Quarter-finals,2021-03-07,False,False,False,Ukraine,England,0,4,48,52,7,10,2,6,42,59,None,4
4,Quarter-finals,2021-03-07,False,False,False,Czech Republic,Denmark,1,2,56,44,16,11,5,7,48,52,None,5

In [38]:
user = os.getenv("POSTGRES_USER")
password = os.getenv("POSTGRES_PASSWORD")

In [29]:
postgres_url = f"postgresql+psycopg2://{user}:{password}@127.0.0.1:5432/euro2020"

In [30]:
engine = create_engine(postgres_url)
euro2020 = engine.connect()
euro2020

In [39]:
df.to_sql("match", euro2020, index=False, if_exists="replace")

In [13]:
postgres_url_cloud = os.getenv("POSTGRES_URL")

In [14]:
engine_cloud = create_engine(postgres_url_cloud)
euro2020_cl = engine_cloud.connect()

In [ ]:
df.to_sql("match", euro2020_cl, index=False, if_exists="replace")